"use strict";


import { Router } from "express";
import userRoutes from './user.routes.js';
import areaRoutes from './area.routes.js';
import authRoutes from './auth.routes.js';
import roleRoutes from './role.routes.js';
import eventRoutes from './event.routes.js';
import noticeRoutes from './notice.routes.js';
import publicNoticeRoutes from './public_notice.routes.js';
import publicAccountingReportRoutes from './public_accounting_report.routes.js';
import publicSponsorshipRoutes from './public_sponsorship.routes.js';
import publicFileAssetRoutes from './public_file_asset.routes.js';
import shiftRoutes from './shift.routes.js';
import taskRoutes from './task.routes.js';
import permissionRoutes from './permission.routes.js';
import healthRoutes from './health.routes.js';
import animalRoutes from './animalConcept/animal.route.js';
import animalDietsRoutes from './animalConcept/animal_diets.route.js';
import animalProfileRoutes from './animalConcept/animal_profile.route.js';
import examRoutes from './animalConcept/exam.route.js';
import fosterAssignmentRoutes from './animalConcept/foster_assignment.route.js';
import fosterHomeRoutes from './animalConcept/foster_home.route.js';
import fosterHomeAllowedAnimalRoutes from './animalConcept/foster_home_allowed_animal.route.js';
import fosterHomeObservationRoutes from './animalConcept/foster_home_observation.route.js';
import hospitalizationRoutes from './animalConcept/hospitalization.route.js';
import intakeRecordRoutes from './animalConcept/intake_record.route.js';
import procedureRoutes from './animalConcept/procedure.route.js';
import vetCheckupRoutes from './animalConcept/vet_checkup.route.js';
import vetClinicRoutes from './animalConcept/vet_clinic.route.js';
import veterinarianRoutes from './animalConcept/veterinarian.route.js';
import registrationShiftRoutes from './registration_shift.routes.js';
import comunaRoutes from './comuna.routes.js';
import regionRoutes from './region.routes.js';
import donationRoutes from './inventoryConcept/donation.routes.js';
import donorRoutes from './inventoryConcept/donor.routes.js';
import donationItemRoutes from './inventoryConcept/donation_item.routes.js';
import fileAssetRoutes from './file_asset.routes.js';
import inventoryRoutes from './inventoryConcept/inventory.routes.js';
import inventoryAdjustmentRoutes from './inventoryConcept/inventory_adjustment.routes.js';
import inventoryAdjustmentDetailRoutes from './inventoryConcept/inventory_adjustment_detail.routes.js';
import inventoryExistenceRoutes from './inventoryConcept/inventory_existence.routes.js';
import inventoryMovementRoutes from './inventoryConcept/inventory_movement.routes.js';
import itemCategoryRoutes from './inventoryConcept/item_category.routes.js';
import itemRoutes from './inventoryConcept/item.routes.js';
import locationRoutes from './inventoryConcept/location.routes.js';
import purchaseRoutes from './inventoryConcept/purchase.routes.js';
import purchaseDetailRoutes from './inventoryConcept/purchase_detail.routes.js';
import stockCountRoutes from './inventoryConcept/stock_count.routes.js';
import stockCountDetailRoutes from './inventoryConcept/stock_count_detail.routes.js';
import supplierRoutes from './inventoryConcept/supplier.routes.js';
import unitOfMeasureRoutes from './inventoryConcept/unit_of_measure.routes.js';
import inventoryReportRoutes from './inventoryConcept/inventory_report.routes.js';
import accountingDashboardRoutes from './financialConcept/accounting_dashboard.routes.js';
import accountingDonationRoutes from './financialConcept/accounting_donation.routes.js';
import transactionCategoryRoutes from './financialConcept/transaction_category.routes.js';
import paymentProviderRoutes from './financialConcept/payment_provider.routes.js';
import transactionRoutes from './financialConcept/transaction.routes.js';
import payableAccountRoutes from './financialConcept/payable_account.routes.js';
import paymentOrderRoutes from './financialConcept/payment_order.routes.js';
import webhookLogRoutes from './financialConcept/webhook_log.routes.js';
import accountingReportRoutes from './financialConcept/accounting_report.routes.js';
import publicMonthlyAccountingReportRoutes from './financialConcept/public_monthly_accounting_report.routes.js';
import sponsorshipPlanRoutes from './financialConcept/sponsorship_plan.routes.js';
import sponsorshipAnimalsRoutes from './financialConcept/sponsorship_animals.routes.js';
import sponsorsRoutes from './financialConcept/sponsors.routes.js';
import sponsorshipsRoutes from './financialConcept/sponsorships.routes.js';
import subscriptionsRoutes from './financialConcept/subscriptions.routes.js';
import subscriptionPaymentsRoutes from './financialConcept/subscription_payments.routes.js';
import paypalDonationRoutes from './paypal/paypalDonation.routes.js';
import paypalWebhookRoutes from './paypal/paypalWebhook.routes.js';

const router = Router();

router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/user', userRoutes);
router.use('/area', areaRoutes);
router.use('/role', roleRoutes);
router.use('/event', eventRoutes);
router.use('/notice', noticeRoutes);
router.use('/public/notices', publicNoticeRoutes);
router.use('/public/accounting-reports', publicAccountingReportRoutes);
router.use('/public/sponsorship', publicSponsorshipRoutes);
router.use('/public/sponsorships', publicSponsorshipRoutes);
router.use('/public/files', publicFileAssetRoutes);
router.use('/shift', shiftRoutes);
router.use('/task', taskRoutes);
router.use('/permission', permissionRoutes);
router.use('/animal', animalRoutes);
router.use('/animal_diets', animalDietsRoutes);
router.use('/animal_profile', animalProfileRoutes);
router.use('/exam', examRoutes);
router.use('/foster_assignment', fosterAssignmentRoutes);
router.use('/foster_home', fosterHomeRoutes);
router.use('/foster_home_allowed_animal', fosterHomeAllowedAnimalRoutes);
router.use('/foster_home_observation', fosterHomeObservationRoutes);
router.use('/hospitalization', hospitalizationRoutes);
router.use('/intake_record', intakeRecordRoutes);
router.use('/procedure', procedureRoutes);
router.use('/vet_checkup', vetCheckupRoutes);
router.use('/vet_clinic', vetClinicRoutes);
router.use('/veterinarian', veterinarianRoutes);
router.use('/shift', registrationShiftRoutes);
router.use('/comuna', comunaRoutes);
router.use('/region', regionRoutes);
router.use('/donation', donationRoutes);
router.use('/donor', donorRoutes);
router.use('/donation_item', donationItemRoutes);
router.use('/files', fileAssetRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/inventory_adjustment', inventoryAdjustmentRoutes);
router.use('/inventory_adjustment_detail', inventoryAdjustmentDetailRoutes);
router.use('/inventory_existence', inventoryExistenceRoutes);
router.use('/inventory_movement', inventoryMovementRoutes);
router.use('/item_category', itemCategoryRoutes);
router.use('/item', itemRoutes);
router.use('/location', locationRoutes);
router.use('/purchase', purchaseRoutes);
router.use('/purchase_detail', purchaseDetailRoutes);
router.use('/stock_count', stockCountRoutes);
router.use('/stock_count_detail', stockCountDetailRoutes);
router.use('/supplier', supplierRoutes);
router.use('/unit_of_measure', unitOfMeasureRoutes);
router.use('/inventory/reports', inventoryReportRoutes);
router.use('/accounting/dashboard', accountingDashboardRoutes);
router.use('/accounting/donations', accountingDonationRoutes);
router.use('/accounting/categories', transactionCategoryRoutes);
router.use('/accounting/payment-providers', paymentProviderRoutes);
router.use('/accounting/transactions', transactionRoutes);
router.use('/accounting/payables', payableAccountRoutes);
router.use('/accounting/payment-orders', paymentOrderRoutes);
router.use('/accounting/webhooks', webhookLogRoutes);
router.use('/accounting/reports', accountingReportRoutes);
router.use('/accounting/public-reports', publicMonthlyAccountingReportRoutes);
router.use('/accounting/sponsorship-plans', sponsorshipPlanRoutes);
router.use('/accounting/sponsorship-animals', sponsorshipAnimalsRoutes);
router.use('/accounting/sponsors', sponsorsRoutes);
router.use('/accounting/sponsorships', sponsorshipsRoutes);
router.use('/accounting/subscriptions', subscriptionsRoutes);
router.use('/accounting/subscription-payments', subscriptionPaymentsRoutes);
router.use('/paypal/donations', paypalDonationRoutes);
router.use('/webhooks/paypal', paypalWebhookRoutes);

export default router;
