import { PERMISSIONS } from "./permissions";

export const DEFAULT_MENU_PATH = "/inicio";

export const NAVIGATION_ITEMS = [
  {
    id: 1,
    label: "Inicio",
    iconKey: "home",
    path: "/inicio",
    order: 1,
    active: true,
    permissions: [PERMISSIONS.HOME.NOTICE_READ, PERMISSIONS.HOME.EVENT_READ],
  },
  {
    id: 2,
    label: "Rescatados",
    iconKey: "animals",
    path: "/rescatados",
    order: 2,
    active: true,
    permissions: [PERMISSIONS.ANIMALS.ANIMAL_READ],
  },
  {
    id: 3,
    label: "Hogar Temporal",
    iconKey: "fosterHome",
    path: "/hogar-temporal",
    order: 3,
    active: true,
    permissionPrefixes: ["animals:foster_home:", "animals:foster_assignment:"],
  },
  {
    id: 4,
    label: "Apadrinamiento",
    iconKey: "sponsorship",
    path: "/apadrinamientos",
    order: 4,
    active: true,
    permissions: [
      PERMISSIONS.ACCOUNTING.SPONSOR_READ,
      PERMISSIONS.ACCOUNTING.SPONSORSHIP_READ,
      PERMISSIONS.ACCOUNTING.SUBSCRIPTION_PAYMENT_READ,
      PERMISSIONS.ACCOUNTING.SPONSORSHIP_PLAN_READ,
    ],
  },
  {
    id: 5,
    label: "Voluntarios",
    iconKey: "volunteers",
    path: "/voluntarios",
    order: 5,
    active: true,
    permissions: [PERMISSIONS.USERS.READ, PERMISSIONS.ROLES.READ],
  },
  {
    id: 6,
    label: "Turnos",
    iconKey: "shifts",
    path: "/turnos",
    order: 6,
    active: true,
    permissions: [PERMISSIONS.SHIFTS.READ],
  },
  {
    id: 7,
    label: "Tareas",
    iconKey: "tasks",
    path: "/tareas",
    order: 7,
    active: true,
    permissions: [
      PERMISSIONS.TASKS.READ_ANY,
      PERMISSIONS.TASKS.READ_AREA,
      PERMISSIONS.TASKS.READ_MINE,
    ],
  },
  {
    id: 8,
    label: "Inventario",
    iconKey: "inventory",
    path: "/inventario",
    order: 8,
    active: true,
    permissions: [
      PERMISSIONS.INVENTORY.READ_ANY,
      PERMISSIONS.INVENTORY.ITEM_READ,
      PERMISSIONS.INVENTORY.MOVEMENT_READ,
      PERMISSIONS.INVENTORY.INITIAL_LOAD_CREATE,
      PERMISSIONS.INVENTORY.DONATION_READ,
      PERMISSIONS.INVENTORY.PURCHASE_READ,
      PERMISSIONS.INVENTORY.STOCK_COUNT_READ,
      PERMISSIONS.INVENTORY.ADJUSTMENT_READ,
      PERMISSIONS.INVENTORY.LOCATION_READ,
      PERMISSIONS.INVENTORY.ITEM_CREATE,
      PERMISSIONS.INVENTORY.ITEM_UPDATE,
      PERMISSIONS.INVENTORY.ITEM_DELETE,
      PERMISSIONS.INVENTORY.ITEM_CATEGORY_READ,
      PERMISSIONS.INVENTORY.ITEM_CATEGORY_CREATE,
      PERMISSIONS.INVENTORY.ITEM_CATEGORY_UPDATE,
      PERMISSIONS.INVENTORY.ITEM_CATEGORY_DELETE,
      PERMISSIONS.INVENTORY.UNIT_READ,
      PERMISSIONS.INVENTORY.UNIT_CREATE,
      PERMISSIONS.INVENTORY.UNIT_UPDATE,
      PERMISSIONS.INVENTORY.UNIT_DELETE,
      PERMISSIONS.INVENTORY.SUPPLIER_READ,
      PERMISSIONS.INVENTORY.SUPPLIER_CREATE,
      PERMISSIONS.INVENTORY.SUPPLIER_UPDATE,
      PERMISSIONS.INVENTORY.SUPPLIER_DELETE,
    ],
  },
  {
    id: 9,
    label: "Contabilidad",
    iconKey: "accounting",
    path: "/contabilidad",
    order: 9,
    active: true,
    permissions: [
      PERMISSIONS.ACCOUNTING.DASHBOARD_READ,
      PERMISSIONS.ACCOUNTING.TRANSACTION_READ,
      PERMISSIONS.ACCOUNTING.PAYABLE_READ,
      PERMISSIONS.ACCOUNTING.CATEGORY_READ,
      PERMISSIONS.ACCOUNTING.PAYMENT_PROVIDER_READ,
      PERMISSIONS.ACCOUNTING.PAYMENT_ORDER_READ,
      PERMISSIONS.ACCOUNTING.WEBHOOK_READ,
      PERMISSIONS.ACCOUNTING.PUBLIC_REPORT_READ,
      PERMISSIONS.ACCOUNTING.DONOR_READ,
    ],
  },
  {
    id: 10,
    label: "Configuracion",
    iconKey: "settings",
    path: "/configuracion",
    order: 10,
    active: true,
    permissions: [PERMISSIONS.SETTINGS.READ],
  },
];
