export const ROLES = {
	ADMINISTRADOR: "Administrador",
	DIRECTIVA: "Directiva",
	ENCARGADO_CONTENIDO: "Encargado de área contenido",
	VOLUNTARIO: "Voluntario",
};

export const ROLES_GESTION_TURNOS_TAREAS = [
	ROLES.ADMINISTRADOR,
	ROLES.DIRECTIVA,
	ROLES.ENCARGADO_CONTENIDO,
	ROLES.VOLUNTARIO,
];

export const ROLES_GESTION_HOME = [
	ROLES.ADMINISTRADOR,
	ROLES.DIRECTIVA,
	ROLES.ENCARGADO_CONTENIDO,
	ROLES.VOLUNTARIO,
];

export const ROLES_GESTION_CONTENIDO = [
	ROLES.ADMINISTRADOR,
	ROLES.DIRECTIVA,
	ROLES.ENCARGADO_CONTENIDO,
];

export const ROLES_ADMINISTRACION = [ROLES.ADMINISTRADOR];

