const ALL_PERMISSION_KEYS = [
  "settings:read",
  "configuration:region:read",
  "configuration:region:create",
  "configuration:region:update",
  "configuration:region:deactivate",
  "configuration:commune:read",
  "configuration:commune:create",
  "configuration:commune:update",
  "configuration:commune:deactivate",
  "configuration:area:read",
  "configuration:area:create",
  "configuration:area:update",
  "configuration:area:deactivate",
  "users:user:read",
  "users:user:create",
  "users:user:update",
  "users:user:delete",
  "users:user_password:reset",
  "users:user_role:assign",
  "users:user_area:assign",
  "role:read",
  "role:create",
  "role:update",
  "role:delete",
  "home:notice:read",
  "home:notice:create",
  "home:notice:update",
  "home:notice:delete",
  "home:event:read",
  "home:event:create",
  "home:event:update",
  "home:event:delete",
  "home:shift:read",
  "home:shift:create",
  "home:shift:update",
  "home:shift:delete",
  "home:shift:register",
  "home:shift:cancel",
  "home:shift:registrations:read",
  "home:shift:registrations:self:read",
  "home:task:read:any",
  "home:task:read:area",
  "home:task:read:mine",
  "home:task:create:any",
  "home:task:create:area",
  "home:task:update:any",
  "home:task:update:area",
  "home:task:update:status:mine",
  "home:task:assign:any",
  "home:task:assign:area",
  "home:task:delete:any",
  "home:task:delete:area",
  "home:task:delete:mine",
  "home:task:history:read:any",
  "home:task:history:read:area",
  "home:task:history:read:mine",
  "home:task:comment:any",
  "home:task:comment:area",
  "home:task:comment:mine",
  "animals:animal:read",
  "animals:animal:create",
  "animals:animal:update",
  "animals:animal:delete",
  "animals:animal_diets:read",
  "animals:animal_diets:create",
  "animals:animal_diets:update",
  "animals:animal_diets:delete",
  "animals:animal_profile:read",
  "animals:animal_profile:create",
  "animals:animal_profile:update",
  "animals:animal_profile:delete",
  "animals:exam:read",
  "animals:exam:create",
  "animals:exam:update",
  "animals:exam:delete",
  "animals:foster_assignment:read",
  "animals:foster_assignment:create",
  "animals:foster_assignment:update",
  "animals:foster_assignment:delete",
  "animals:foster_home:read",
  "animals:foster_home:create",
  "animals:foster_home:update",
  "animals:foster_home:delete",
  "animals:foster_home_observation:read",
  "animals:hospitalization:read",
  "animals:hospitalization:create",
  "animals:hospitalization:update",
  "animals:hospitalization:delete",
  "animals:intake_record:read",
  "animals:intake_record:create",
  "animals:intake_record:update",
  "animals:intake_record:delete",
  "animals:procedure:read",
  "animals:procedure:create",
  "animals:procedure:update",
  "animals:procedure:delete",
  "animals:vet_checkup:read",
  "animals:vet_checkup:create",
  "animals:vet_checkup:update",
  "animals:vet_checkup:delete",
  "animals:vet_clinic:read",
  "animals:vet_clinic:create",
  "animals:vet_clinic:update",
  "animals:vet_clinic:delete",
  "animals:veterinarian:read",
  "animals:veterinarian:create",
  "animals:veterinarian:update",
  "animals:veterinarian:delete",
  "inventory:donation:read",
  "inventory:donation:create",
  "inventory:donation:update",
  "inventory:donation:delete",
  "inventory:donation_item:read",
  "inventory:donation_item:create",
  "inventory:donation_item:update",
  "inventory:donation_item:delete",
  "inventory:inventory_adjustment:read",
  "inventory:inventory_adjustment:create",
  "inventory:inventory_adjustment:update",
  "inventory:inventory_adjustment:delete",
  "inventory:inventory_adjustment_detail:read",
  "inventory:inventory_adjustment_detail:create",
  "inventory:inventory_adjustment_detail:update",
  "inventory:inventory_adjustment_detail:delete",
  "inventory:inventory_existence:read",
  "inventory:inventory_movement:read",
  "inventory:inventory_movement:create",
  "inventory:inventory_movement:update",
  "inventory:inventory_movement:delete",
  "inventory:purchase:read",
  "inventory:purchase:create",
  "inventory:purchase:update",
  "inventory:purchase:delete",
  "inventory:purchase_detail:read",
  "inventory:purchase_detail:create",
  "inventory:purchase_detail:update",
  "inventory:purchase_detail:delete",
  "inventory:read:any",
  "inventory:read:location",
  "inventory:movement:create:any",
  "inventory:movement:create:location",
  "inventory:adjustment:create:any",
  "inventory:adjustment:create:location",
  "inventory:adjustment:apply:any",
  "inventory:initial_load:create",
  "inventory:catalog:read",
  "inventory:catalog:create",
  "inventory:catalog:update",
  "inventory:catalog:delete",
  "inventory:item_category:read",
  "inventory:item_category:create",
  "inventory:item_category:update",
  "inventory:item_category:delete",
  "inventory:item:read",
  "inventory:item:create",
  "inventory:item:update",
  "inventory:item:delete",
  "inventory:location:read",
  "inventory:location:create",
  "inventory:location:update",
  "inventory:location:delete",
  "inventory:stock_count:read",
  "inventory:stock_count:create",
  "inventory:stock_count:create:location",
  "inventory:stock_count:update",
  "inventory:stock_count:delete",
  "inventory:stock_count_detail:read",
  "inventory:stock_count_detail:create",
  "inventory:stock_count_detail:update",
  "inventory:stock_count_detail:delete",
  "inventory:supplier:read",
  "inventory:supplier:create",
  "inventory:supplier:update",
  "inventory:supplier:delete",
  "inventory:report:export",
  "inventory:unit_of_measure:read",
  "inventory:unit_of_measure:create",
  "inventory:unit_of_measure:update",
  "inventory:unit_of_measure:delete",
  "accounting:dashboard:read",
  "accounting:transaction:read",
  "accounting:transaction:create",
  "accounting:transaction:update",
  "accounting:transaction:cancel",
  "accounting:payable:read",
  "accounting:payable:create",
  "accounting:payable:update",
  "accounting:payable:pay",
  "accounting:payable:cancel",
  "accounting:donor:read",
  "accounting:donor:create",
  "accounting:donor:update",
  "accounting:sponsor:read",
  "accounting:sponsor:create",
  "accounting:sponsor:update",
  "accounting:sponsorship:read",
  "accounting:sponsorship:create",
  "accounting:sponsorship:update",
  "accounting:sponsorship:cancel",
  "accounting:sponsorship_plan:read",
  "accounting:sponsorship_plan:create",
  "accounting:sponsorship_plan:update",
  "accounting:sponsorship_plan:delete",
  "accounting:subscription:read",
  "accounting:subscription:cancel",
  "accounting:subscription:sync",
  "accounting:subscription_payment:read",
  "accounting:subscription_payment:create",
  "accounting:category:read",
  "accounting:category:create",
  "accounting:category:update",
  "accounting:category:delete",
  "accounting:payment_provider:read",
  "accounting:payment_provider:create",
  "accounting:payment_provider:update",
  "accounting:payment_provider:delete",
  "accounting:payment_order:read",
  "accounting:payment_order:create",
  "accounting:payment_order:update",
  "accounting:payment_order:cancel",
  "accounting:report:export",
  "accounting:public_report:read",
  "accounting:public_report:create",
  "accounting:public_report:publish",
  "accounting:public_report:archive",
  "accounting:donation_refund:create",
  "accounting:webhook:read",
  "accounting:webhook:retry",
  "files:file:read",
  "files:file:upload",
  "files:file:download",
  "files:file:delete",
  "files:file:update",
  "files:file:manage_visibility",
  "files:animal:read",
  "files:animal:upload",
  "files:animal:delete",
  "files:animal_clinical:read",
  "files:animal_clinical:upload",
  "files:animal_clinical:delete",
  "files:accounting:read",
  "files:accounting:upload",
  "files:accounting:delete",
  "files:user_document:read",
  "files:user_document:upload",
  "files:user_document:delete",
];

export const PERMISSION_MODULE_ORDER = [
  "Usuarios",
  "Roles y permisos",
  "Inicio",
  "Animales rescatados",
  "Hogar temporal",
  "Turnos",
  "Tareas",
  "Inventario",
  "Donaciones",
  "Archivos",
  "Contabilidad",
  "Configuracion",
  "Otros",
];

export const PERMISSION_GROUP_ORDER = [
  "Consulta",
  "Creación",
  "Edición",
  "Eliminación",
  "Asignaciones",
  "Estados",
  "Historial",
  "Administracion",
  "Reportes",
  "Otros",
];

function createEntry({
  key,
  label,
  description,
  module,
  group,
  action,
  isDangerous = false,
  sortOrder,
}) {
  return {
    key,
    label,
    description,
    module,
    group,
    action,
    isDangerous,
    sortOrder,
  };
}

function createCrudPermissionSet({
  prefix,
  module,
  subjectPlural,
  baseOrder,
  readDangerous = false,
  createDangerous = false,
  updateDangerous = false,
  deleteDangerous = true,
  readLabel = `Ver ${subjectPlural}`,
  createLabel = `Crear ${subjectPlural}`,
  updateLabel = `Editar ${subjectPlural}`,
  deleteLabel = `Eliminar ${subjectPlural}`,
  readDescription = `Permite consultar el listado y detalle de ${subjectPlural}.`,
  createDescription = `Permite crear ${subjectPlural}.`,
  updateDescription = `Permite editar y actualizar ${subjectPlural}.`,
  deleteDescription = `Permite eliminar ${subjectPlural}.`,
}) {
  return [
    createEntry({
      key: `${prefix}:read`,
      label: readLabel,
      description: readDescription,
      module,
      group: "Consulta",
      action: "read",
      isDangerous: readDangerous,
      sortOrder: baseOrder + 10,
    }),
    createEntry({
      key: `${prefix}:create`,
      label: createLabel,
      description: createDescription,
      module,
      group: "Creación",
      action: "create",
      isDangerous: createDangerous,
      sortOrder: baseOrder + 20,
    }),
    createEntry({
      key: `${prefix}:update`,
      label: updateLabel,
      description: updateDescription,
      module,
      group: "Edición",
      action: "update",
      isDangerous: updateDangerous,
      sortOrder: baseOrder + 30,
    }),
    createEntry({
      key: `${prefix}:delete`,
      label: deleteLabel,
      description: deleteDescription,
      module,
      group: "Eliminación",
      action: "delete",
      isDangerous: deleteDangerous,
      sortOrder: baseOrder + 40,
    }),
  ];
}

const catalogEntries = [
  createEntry({
    key: "settings:read",
    label: "Ver configuracion del sistema",
    description: "Permite acceder al módulo de configuracion y consultar sus datos base.",
    module: "Configuracion",
    group: "Consulta",
    action: "read",
    isDangerous: false,
    sortOrder: 10,
  }),
  createEntry({
    key: "configuration:region:read",
    label: "Ver regiones",
    description: "Permite consultar el catálogo de regiones.",
    module: "Configuracion",
    group: "Consulta",
    action: "read",
    isDangerous: false,
    sortOrder: 20,
  }),
  createEntry({
    key: "configuration:region:create",
    label: "Crear regiones",
    description: "Permite registrar nuevas regiones en la configuración territorial.",
    module: "Configuracion",
    group: "Creación",
    action: "create",
    isDangerous: false,
    sortOrder: 30,
  }),
  createEntry({
    key: "configuration:region:update",
    label: "Editar regiones",
    description: "Permite modificar datos de regiones existentes.",
    module: "Configuracion",
    group: "Edición",
    action: "update",
    isDangerous: false,
    sortOrder: 40,
  }),
  createEntry({
    key: "configuration:region:deactivate",
    label: "Activar o desactivar regiones",
    description: "Permite activar o desactivar regiones sin eliminarlas físicamente.",
    module: "Configuracion",
    group: "Estados",
    action: "toggle_active",
    isDangerous: true,
    sortOrder: 50,
  }),
  createEntry({
    key: "configuration:commune:read",
    label: "Ver comunas",
    description: "Permite consultar el catálogo de comunas.",
    module: "Configuracion",
    group: "Consulta",
    action: "read",
    isDangerous: false,
    sortOrder: 60,
  }),
  createEntry({
    key: "configuration:commune:create",
    label: "Crear comunas",
    description: "Permite registrar nuevas comunas asociadas a una región.",
    module: "Configuracion",
    group: "Creación",
    action: "create",
    isDangerous: false,
    sortOrder: 70,
  }),
  createEntry({
    key: "configuration:commune:update",
    label: "Editar comunas",
    description: "Permite modificar datos de comunas existentes.",
    module: "Configuracion",
    group: "Edición",
    action: "update",
    isDangerous: false,
    sortOrder: 80,
  }),
  createEntry({
    key: "configuration:commune:deactivate",
    label: "Activar o desactivar comunas",
    description: "Permite activar o desactivar comunas sin eliminarlas físicamente.",
    module: "Configuracion",
    group: "Estados",
    action: "toggle_active",
    isDangerous: true,
    sortOrder: 90,
  }),

  createEntry({
    key: "configuration:area:read",
    label: "Ver áreas",
    description: "Permite consultar el catálogo de áreas internas de la fundación.",
    module: "Configuracion",
    group: "Consulta",
    action: "read",
    isDangerous: false,
    sortOrder: 100,
  }),
  createEntry({
    key: "configuration:area:create",
    label: "Crear áreas",
    description: "Permite registrar nuevas áreas internas para usuarios y tareas.",
    module: "Configuracion",
    group: "Creación",
    action: "create",
    isDangerous: false,
    sortOrder: 110,
  }),
  createEntry({
    key: "configuration:area:update",
    label: "Editar áreas",
    description: "Permite modificar nombre, clave, descripción y estado de áreas existentes.",
    module: "Configuracion",
    group: "Edición",
    action: "update",
    isDangerous: false,
    sortOrder: 120,
  }),
  createEntry({
    key: "configuration:area:deactivate",
    label: "Activar o desactivar áreas",
    description: "Permite activar o desactivar áreas sin eliminarlas físicamente ni perder historial.",
    module: "Configuracion",
    group: "Estados",
    action: "toggle_active",
    isDangerous: true,
    sortOrder: 130,
  }),

  ...createCrudPermissionSet({
    prefix: "users:user",
    module: "Usuarios",
    subjectPlural: "usuarios",
    baseOrder: 0,
  }),
  createEntry({
    key: "users:user_role:assign",
    label: "Asignar roles a usuarios",
    description: "Permite asignar o reemplazar los roles asociados a un usuario.",
    module: "Usuarios",
    group: "Asignaciones",
    action: "assign",
    isDangerous: true,
    sortOrder: 60,
  }),
  createEntry({
    key: "users:user_area:assign",
    label: "Asignar áreas a usuarios",
    description: "Permite asignar o reemplazar las áreas asociadas a un usuario.",
    module: "Usuarios",
    group: "Asignaciones",
    action: "assign",
    isDangerous: false,
    sortOrder: 70,
  }),
  createEntry({
    key: "users:user_password:reset",
    label: "Restablecer contraseñas de usuarios",
    description: "Permite establecer una nueva contraseña para otro usuario sin conocer su contraseña actual.",
    module: "Usuarios",
    group: "Administracion",
    action: "reset_password",
    isDangerous: true,
    sortOrder: 80,
  }),

  ...createCrudPermissionSet({
    prefix: "role",
    module: "Roles y permisos",
    subjectPlural: "roles",
    baseOrder: 0,
    createDangerous: true,
    updateDangerous: true,
    readLabel: "Ver roles y permisos",
    createLabel: "Crear roles",
    updateLabel: "Editar roles",
    deleteLabel: "Eliminar roles",
    readDescription: "Permite consultar roles y permisos asociados.",
    createDescription: "Permite crear roles y asignar permisos.",
    updateDescription: "Permite editar roles y cambiar los permisos asociados.",
    deleteDescription: "Permite eliminar roles existentes.",
  }),

  ...createCrudPermissionSet({
    prefix: "home:notice",
    module: "Inicio",
    subjectPlural: "avisos",
    baseOrder: 0,
  }),
  ...createCrudPermissionSet({
    prefix: "home:event",
    module: "Inicio",
    subjectPlural: "eventos",
    baseOrder: 100,
  }),

  ...createCrudPermissionSet({
    prefix: "home:shift",
    module: "Turnos",
    subjectPlural: "turnos",
    baseOrder: 0,
  }),
  createEntry({
    key: "home:shift:register",
    label: "Inscribirse a turnos",
    description: "Permite registrar la inscripción de un usuario a un turno disponible.",
    module: "Turnos",
    group: "Asignaciones",
    action: "register",
    isDangerous: false,
    sortOrder: 60,
  }),
  createEntry({
    key: "home:shift:cancel",
    label: "Cancelar inscripciones a turnos",
    description: "Permite cancelar una inscripción existente a un turno.",
    module: "Turnos",
    group: "Estados",
    action: "cancel",
    isDangerous: true,
    sortOrder: 70,
  }),
  createEntry({
    key: "home:shift:registrations:read",
    label: "Ver inscripciones a turnos",
    description: "Permite revisar las inscripciones de todos los usuarios a los turnos.",
    module: "Turnos",
    group: "Consulta",
    action: "read",
    isDangerous: false,
    sortOrder: 80,
  }),
  createEntry({
    key: "home:shift:registrations:self:read",
    label: "Ver mis inscripciones a turnos",
    description: "Permite revisar las inscripciones del propio usuario a los turnos.",
    module: "Turnos",
    group: "Consulta",
    action: "read",
    isDangerous: false,
    sortOrder: 90,
  }),

  createEntry({
    key: "home:task:read:any",
    label: "Ver todas las tareas",
    description: "Permite consultar todas las tareas visibles en el sistema.",
    module: "Tareas",
    group: "Consulta",
    action: "read",
    isDangerous: false,
    sortOrder: 10,
  }),
  createEntry({
    key: "home:task:read:area",
    label: "Ver tareas de mi área",
    description: "Permite consultar tareas dentro del alcance del área del usuario.",
    module: "Tareas",
    group: "Consulta",
    action: "read",
    isDangerous: false,
    sortOrder: 20,
  }),
  createEntry({
    key: "home:task:read:mine",
    label: "Ver mis tareas",
    description: "Permite consultar las tareas propias o asignadas al usuario.",
    module: "Tareas",
    group: "Consulta",
    action: "read",
    isDangerous: false,
    sortOrder: 30,
  }),
  createEntry({
    key: "home:task:create:any",
    label: "Crear tareas globales",
    description: "Permite crear tareas sin restriccion de área.",
    module: "Tareas",
    group: "Creación",
    action: "create",
    isDangerous: false,
    sortOrder: 40,
  }),
  createEntry({
    key: "home:task:create:area",
    label: "Crear tareas de mi área",
    description: "Permite crear tareas dentro del área asociada al usuario.",
    module: "Tareas",
    group: "Creación",
    action: "create",
    isDangerous: false,
    sortOrder: 50,
  }),
  createEntry({
    key: "home:task:update:any",
    label: "Editar cualquier tarea",
    description: "Permite editar tareas de cualquier área visible.",
    module: "Tareas",
    group: "Edición",
    action: "update",
    isDangerous: false,
    sortOrder: 60,
  }),
  createEntry({
    key: "home:task:update:area",
    label: "Editar tareas de mi área",
    description: "Permite editar tareas dentro del área del usuario.",
    module: "Tareas",
    group: "Edición",
    action: "update",
    isDangerous: false,
    sortOrder: 70,
  }),
  createEntry({
    key: "home:task:update:status:mine",
    label: "Cambiar estado de mis tareas",
    description: "Permite actualizar el estado de las tareas propias o asignadas al usuario.",
    module: "Tareas",
    group: "Estados",
    action: "change_status",
    isDangerous: false,
    sortOrder: 80,
  }),
  createEntry({
    key: "home:task:assign:any",
    label: "Asignar tareas globalmente",
    description: "Permite asignar tareas a usuarios de cualquier área.",
    module: "Tareas",
    group: "Asignaciones",
    action: "assign",
    isDangerous: false,
    sortOrder: 90,
  }),
  createEntry({
    key: "home:task:assign:area",
    label: "Asignar tareas en mi área",
    description: "Permite asignar tareas solo dentro del área del usuario.",
    module: "Tareas",
    group: "Asignaciones",
    action: "assign",
    isDangerous: false,
    sortOrder: 100,
  }),
  createEntry({
    key: "home:task:delete:any",
    label: "Eliminar cualquier tarea",
    description: "Permite eliminar tareas de cualquier área visible.",
    module: "Tareas",
    group: "Eliminación",
    action: "delete",
    isDangerous: true,
    sortOrder: 110,
  }),
  createEntry({
    key: "home:task:delete:area",
    label: "Eliminar tareas de mi área",
    description: "Permite eliminar tareas dentro del área del usuario.",
    module: "Tareas",
    group: "Eliminación",
    action: "delete",
    isDangerous: true,
    sortOrder: 120,
  }),
  createEntry({
    key: "home:task:delete:mine",
    label: "Eliminar mis tareas",
    description: "Permite eliminar tareas propias o asignadas al usuario cuando el flujo lo permita.",
    module: "Tareas",
    group: "Eliminación",
    action: "delete",
    isDangerous: true,
    sortOrder: 130,
  }),
  createEntry({
    key: "home:task:history:read:any",
    label: "Ver historial global de tareas",
    description: "Permite consultar el historial completo de cambios de las tareas.",
    module: "Tareas",
    group: "Historial",
    action: "read_history",
    isDangerous: false,
    sortOrder: 140,
  }),
  createEntry({
    key: "home:task:history:read:area",
    label: "Ver historial de tareas de mi área",
    description: "Permite consultar el historial de tareas dentro del área del usuario.",
    module: "Tareas",
    group: "Historial",
    action: "read_history",
    isDangerous: false,
    sortOrder: 150,
  }),
  createEntry({
    key: "home:task:history:read:mine",
    label: "Ver historial de mis tareas",
    description: "Permite consultar el historial de las tareas propias o asignadas al usuario.",
    module: "Tareas",
    group: "Historial",
    action: "read_history",
    isDangerous: false,
    sortOrder: 160,
  }),
  createEntry({
    key: "home:task:comment:any",
    label: "Comentar cualquier tarea",
    description: "Permite agregar comentarios a tareas de cualquier área visible.",
    module: "Tareas",
    group: "Otros",
    action: "comment",
    isDangerous: false,
    sortOrder: 170,
  }),
  createEntry({
    key: "home:task:comment:area",
    label: "Comentar tareas de mi área",
    description: "Permite agregar comentarios a tareas dentro del área del usuario.",
    module: "Tareas",
    group: "Otros",
    action: "comment",
    isDangerous: false,
    sortOrder: 180,
  }),
  createEntry({
    key: "home:task:comment:mine",
    label: "Comentar mis tareas",
    description: "Permite agregar comentarios a tareas propias o asignadas al usuario.",
    module: "Tareas",
    group: "Otros",
    action: "comment",
    isDangerous: false,
    sortOrder: 190,
  }),

  ...createCrudPermissionSet({
    prefix: "animals:animal",
    module: "Animales rescatados",
    subjectPlural: "animales rescatados",
    baseOrder: 0,
  }),
  ...createCrudPermissionSet({
    prefix: "animals:animal_diets",
    module: "Animales rescatados",
    subjectPlural: "dietas de animales",
    baseOrder: 100,
  }),
  ...createCrudPermissionSet({
    prefix: "animals:animal_profile",
    module: "Animales rescatados",
    subjectPlural: "perfiles de animales",
    baseOrder: 200,
  }),
  ...createCrudPermissionSet({
    prefix: "animals:exam",
    module: "Animales rescatados",
    subjectPlural: "exámenes veterinarios",
    baseOrder: 300,
  }),
  ...createCrudPermissionSet({
    prefix: "animals:hospitalization",
    module: "Animales rescatados",
    subjectPlural: "hospitalizaciones",
    baseOrder: 400,
  }),
  ...createCrudPermissionSet({
    prefix: "animals:intake_record",
    module: "Animales rescatados",
    subjectPlural: "registros de ingreso",
    baseOrder: 500,
  }),
  ...createCrudPermissionSet({
    prefix: "animals:procedure",
    module: "Animales rescatados",
    subjectPlural: "procedimientos veterinarios",
    baseOrder: 600,
  }),
  ...createCrudPermissionSet({
    prefix: "animals:vet_checkup",
    module: "Animales rescatados",
    subjectPlural: "controles veterinarios",
    baseOrder: 700,
  }),
  ...createCrudPermissionSet({
    prefix: "animals:vet_clinic",
    module: "Animales rescatados",
    subjectPlural: "clínicas veterinarias",
    baseOrder: 800,
    deleteLabel: "Desactivar clínicas veterinarias",
    deleteDescription: "Permite desactivar clínicas veterinarias sin eliminarlas físicamente.",
  }),
  ...createCrudPermissionSet({
    prefix: "animals:veterinarian",
    module: "Animales rescatados",
    subjectPlural: "veterinarios",
    baseOrder: 900,
    deleteLabel: "Desactivar veterinarios",
    deleteDescription: "Permite desactivar veterinarios sin eliminar su trazabilidad clínica.",
  }),

  ...createCrudPermissionSet({
    prefix: "animals:foster_home",
    module: "Hogar temporal",
    subjectPlural: "hogares temporales",
    baseOrder: 0,
  }),
  ...createCrudPermissionSet({
    prefix: "animals:foster_assignment",
    module: "Hogar temporal",
    subjectPlural: "asignaciones de hogar temporal",
    baseOrder: 100,
    deleteLabel: "Eliminar asignaciones de hogar temporal",
    deleteDescription: "Permite eliminar asignaciones de animales a hogares temporales.",
  }),
  createEntry({
    key: "animals:foster_home_observation:read",
    label: "Ver observaciones de hogares temporales",
    description: "Permite visualizar observaciones sensibles asociadas a hogares temporales.",
    module: "Hogar temporal",
    group: "Consulta",
    action: "read",
    isDangerous: true,
    sortOrder: 210,
  }),

  createEntry({
    key: "inventory:read:any",
    label: "Ver inventario global",
    description: "Permite consultar el resumen y detalle del inventario de todas las ubicaciones.",
    module: "Inventario",
    group: "Consulta",
    action: "read",
    isDangerous: false,
    sortOrder: 10,
  }),
  createEntry({
    key: "inventory:read:location",
    label: "Ver inventario de mi ubicación",
    description: "Permite consultar el inventario dentro de la ubicación asociada al usuario.",
    module: "Inventario",
    group: "Consulta",
    action: "read",
    isDangerous: false,
    sortOrder: 20,
  }),
  createEntry({
    key: "inventory:inventory_existence:read",
    label: "Ver existencias de inventario",
    description: "Permite consultar lotes y existencias especificas del inventario.",
    module: "Inventario",
    group: "Consulta",
    action: "read",
    isDangerous: false,
    sortOrder: 30,
  }),
  createEntry({
    key: "inventory:inventory_movement:read",
    label: "Ver movimientos de inventario",
    description: "Permite consultar el historial de movimientos de inventario.",
    module: "Inventario",
    group: "Historial",
    action: "read_history",
    isDangerous: false,
    sortOrder: 40,
  }),
  createEntry({
    key: "inventory:inventory_movement:create",
    label: "Crear registros de movimientos de inventario",
    description: "Permite crear registros de movimientos dentro del historial de inventario.",
    module: "Inventario",
    group: "Creación",
    action: "create",
    isDangerous: true,
    sortOrder: 50,
  }),
  createEntry({
    key: "inventory:inventory_movement:update",
    label: "Editar registros de movimientos de inventario",
    description: "Permite editar registros existentes de movimientos de inventario.",
    module: "Inventario",
    group: "Edición",
    action: "update",
    isDangerous: true,
    sortOrder: 60,
  }),
  createEntry({
    key: "inventory:inventory_movement:delete",
    label: "Eliminar registros de movimientos de inventario",
    description: "Permite eliminar registros del historial de movimientos de inventario.",
    module: "Inventario",
    group: "Eliminación",
    action: "delete",
    isDangerous: true,
    sortOrder: 70,
  }),
  createEntry({
    key: "inventory:movement:create:any",
    label: "Registrar consumos, salidas y traslados globales",
    description: "Permite ejecutar movimientos transaccionales de inventario sobre cualquier ubicación.",
    module: "Inventario",
    group: "Creación",
    action: "create",
    isDangerous: true,
    sortOrder: 80,
  }),
  createEntry({
    key: "inventory:movement:create:location",
    label: "Registrar consumos, salidas y traslados en mi ubicación",
    description: "Permite ejecutar movimientos transaccionales de inventario dentro de la ubicación del usuario.",
    module: "Inventario",
    group: "Creación",
    action: "create",
    isDangerous: true,
    sortOrder: 90,
  }),
  createEntry({
    key: "inventory:initial_load:create",
    label: "Registrar cargas iniciales de inventario",
    description: "Permite crear cargas iniciales de stock en ubicaciones del inventario.",
    module: "Inventario",
    group: "Creación",
    action: "create",
    isDangerous: true,
    sortOrder: 100,
  }),
  ...createCrudPermissionSet({
    prefix: "inventory:catalog",
    module: "Inventario",
    subjectPlural: "catálogo general de inventario",
    baseOrder: 200,
    readDescription: "Permite consultar vistas generales del catálogo transversal de inventario.",
    createDescription: "Permite crear registros dentro del catálogo transversal de inventario.",
    updateDescription: "Permite editar registros dentro del catálogo transversal de inventario.",
    deleteDescription: "Permite eliminar registros dentro del catálogo transversal de inventario.",
  }),
  ...createCrudPermissionSet({
    prefix: "inventory:item_category",
    module: "Inventario",
    subjectPlural: "categorias de items",
    baseOrder: 300,
  }),
  ...createCrudPermissionSet({
    prefix: "inventory:item",
    module: "Inventario",
    subjectPlural: "items de inventario",
    baseOrder: 400,
  }),
  ...createCrudPermissionSet({
    prefix: "inventory:location",
    module: "Inventario",
    subjectPlural: "ubicaciones de inventario",
    baseOrder: 500,
  }),
  ...createCrudPermissionSet({
    prefix: "inventory:unit_of_measure",
    module: "Inventario",
    subjectPlural: "unidades de medida",
    baseOrder: 600,
  }),
  ...createCrudPermissionSet({
    prefix: "inventory:supplier",
    module: "Inventario",
    subjectPlural: "proveedores de inventario",
    baseOrder: 700,
  }),
  createEntry({
    key: "inventory:report:export",
    label: "Exportar reportes de inventario",
    description: "Permite exportar reportes internos de inventario cuando la fase de exportación este habilitada.",
    module: "Inventario",
    group: "Reportes",
    action: "export",
    isDangerous: false,
    sortOrder: 750,
  }),
  ...createCrudPermissionSet({
    prefix: "inventory:donation",
    module: "Inventario",
    subjectPlural: "donaciones de inventario",
    baseOrder: 800,
  }),
  ...createCrudPermissionSet({
    prefix: "inventory:donation_item",
    module: "Inventario",
    subjectPlural: "líneas de donación de inventario",
    baseOrder: 900,
  }),
  ...createCrudPermissionSet({
    prefix: "inventory:purchase",
    module: "Inventario",
    subjectPlural: "compras de inventario",
    baseOrder: 1000,
  }),
  ...createCrudPermissionSet({
    prefix: "inventory:purchase_detail",
    module: "Inventario",
    subjectPlural: "detalles de compras de inventario",
    baseOrder: 1100,
  }),
  ...createCrudPermissionSet({
    prefix: "inventory:stock_count",
    module: "Inventario",
    subjectPlural: "conteos fisicos",
    baseOrder: 1200,
    createDangerous: true,
    updateDangerous: true,
  }),
  createEntry({
    key: "inventory:stock_count:create:location",
    label: "Crear conteos fisicos en mi ubicación",
    description: "Permite crear conteos fisicos solo dentro de la ubicación del usuario.",
    module: "Inventario",
    group: "Creación",
    action: "create",
    isDangerous: true,
    sortOrder: 1230,
  }),
  ...createCrudPermissionSet({
    prefix: "inventory:stock_count_detail",
    module: "Inventario",
    subjectPlural: "detalles de conteos fisicos",
    baseOrder: 1300,
    createDangerous: true,
    updateDangerous: true,
  }),
  ...createCrudPermissionSet({
    prefix: "inventory:inventory_adjustment",
    module: "Inventario",
    subjectPlural: "ajustes de inventario",
    baseOrder: 1400,
    createDangerous: true,
    updateDangerous: true,
  }),
  ...createCrudPermissionSet({
    prefix: "inventory:inventory_adjustment_detail",
    module: "Inventario",
    subjectPlural: "detalles de ajustes de inventario",
    baseOrder: 1500,
    createDangerous: true,
    updateDangerous: true,
  }),
  createEntry({
    key: "inventory:adjustment:create:any",
    label: "Crear ajustes de inventario globales",
    description: "Permite generar ajustes de inventario para cualquier ubicación.",
    module: "Inventario",
    group: "Creación",
    action: "create",
    isDangerous: true,
    sortOrder: 1610,
  }),
  createEntry({
    key: "inventory:adjustment:create:location",
    label: "Crear ajustes de inventario en mi ubicación",
    description: "Permite generar ajustes de inventario dentro de la ubicación del usuario.",
    module: "Inventario",
    group: "Creación",
    action: "create",
    isDangerous: true,
    sortOrder: 1620,
  }),
  createEntry({
    key: "inventory:adjustment:apply:any",
    label: "Aplicar ajustes de inventario globales",
    description: "Permite aplicar ajustes pendientes y modificar stock real en cualquier ubicación.",
    module: "Inventario",
    group: "Estados",
    action: "apply",
    isDangerous: true,
    sortOrder: 1630,
  }),

  createEntry({
    key: "files:file:read",
    label: "Ver archivos generales",
    description: "Permite consultar archivos transversales y sus metadatos basicos.",
    module: "Archivos",
    group: "Consulta",
    action: "read",
    isDangerous: false,
    sortOrder: 10,
  }),
  createEntry({
    key: "files:file:upload",
    label: "Subir archivos generales",
    description: "Permite cargar archivos transversales en contextos generales del sistema.",
    module: "Archivos",
    group: "Creación",
    action: "upload",
    isDangerous: false,
    sortOrder: 20,
  }),
  createEntry({
    key: "files:file:download",
    label: "Descargar archivos generales",
    description: "Permite descargar archivos generales autorizados desde el sistema.",
    module: "Archivos",
    group: "Consulta",
    action: "download",
    isDangerous: false,
    sortOrder: 30,
  }),
  createEntry({
    key: "files:file:update",
    label: "Actualizar archivos generales",
    description: "Permite cambiar configuraciones seguras de archivos generales, como marcar destacados cuando el flujo lo permita.",
    module: "Archivos",
    group: "Edición",
    action: "update",
    isDangerous: true,
    sortOrder: 40,
  }),
  createEntry({
    key: "files:file:manage_visibility",
    label: "Gestionar visibilidad pública de archivos",
    description: "Permite definir si un archivo general puede exponerse publicamente.",
    module: "Archivos",
    group: "Administracion",
    action: "manage_visibility",
    isDangerous: true,
    sortOrder: 50,
  }),
  createEntry({
    key: "files:file:delete",
    label: "Eliminar archivos generales",
    description: "Permite eliminar archivos generales del sistema de forma controlada.",
    module: "Archivos",
    group: "Eliminación",
    action: "delete",
    isDangerous: true,
    sortOrder: 60,
  }),
  createEntry({
    key: "files:animal:read",
    label: "Ver archivos de animales",
    description: "Permite consultar archivos generales asociados a animales rescatados.",
    module: "Archivos",
    group: "Consulta",
    action: "read",
    isDangerous: false,
    sortOrder: 110,
  }),
  createEntry({
    key: "files:animal:upload",
    label: "Subir archivos de animales",
    description: "Permite cargar archivos e imágenes generales asociados a animales.",
    module: "Archivos",
    group: "Creación",
    action: "upload",
    isDangerous: false,
    sortOrder: 120,
  }),
  createEntry({
    key: "files:animal:delete",
    label: "Eliminar archivos de animales",
    description: "Permite eliminar archivos generales asociados a animales.",
    module: "Archivos",
    group: "Eliminación",
    action: "delete",
    isDangerous: true,
    sortOrder: 130,
  }),
  createEntry({
    key: "files:animal_clinical:read",
    label: "Ver adjuntos clinicos de animales",
    description: "Permite consultar exámenes, informes o adjuntos clinicos privados de animales.",
    module: "Archivos",
    group: "Consulta",
    action: "read",
    isDangerous: true,
    sortOrder: 210,
  }),
  createEntry({
    key: "files:animal_clinical:upload",
    label: "Subir adjuntos clinicos de animales",
    description: "Permite cargar exámenes, informes o adjuntos clinicos privados de animales.",
    module: "Archivos",
    group: "Creación",
    action: "upload",
    isDangerous: true,
    sortOrder: 220,
  }),
  createEntry({
    key: "files:animal_clinical:delete",
    label: "Eliminar adjuntos clinicos de animales",
    description: "Permite eliminar adjuntos clinicos privados asociados a animales.",
    module: "Archivos",
    group: "Eliminación",
    action: "delete",
    isDangerous: true,
    sortOrder: 230,
  }),
  createEntry({
    key: "files:accounting:read",
    label: "Ver adjuntos contables",
    description: "Permite consultar comprobantes y adjuntos privados del módulo contable.",
    module: "Archivos",
    group: "Consulta",
    action: "read",
    isDangerous: true,
    sortOrder: 310,
  }),
  createEntry({
    key: "files:accounting:upload",
    label: "Subir adjuntos contables",
    description: "Permite cargar comprobantes y adjuntos privados para contabilidad.",
    module: "Archivos",
    group: "Creación",
    action: "upload",
    isDangerous: true,
    sortOrder: 320,
  }),
  createEntry({
    key: "files:accounting:delete",
    label: "Eliminar adjuntos contables",
    description: "Permite eliminar comprobantes y adjuntos privados del módulo contable.",
    module: "Archivos",
    group: "Eliminación",
    action: "delete",
    isDangerous: true,
    sortOrder: 330,
  }),
  createEntry({
    key: "files:user_document:read",
    label: "Ver documentos de usuarios",
    description: "Permite consultar contratos y documentos privados asociados a usuarios internos.",
    module: "Archivos",
    group: "Consulta",
    action: "read",
    isDangerous: true,
    sortOrder: 410,
  }),
  createEntry({
    key: "files:user_document:upload",
    label: "Subir documentos de usuarios",
    description: "Permite cargar contratos y documentos privados asociados a usuarios internos.",
    module: "Archivos",
    group: "Creación",
    action: "upload",
    isDangerous: true,
    sortOrder: 420,
  }),
  createEntry({
    key: "files:user_document:delete",
    label: "Eliminar documentos de usuarios",
    description: "Permite eliminar contratos y documentos privados asociados a usuarios internos.",
    module: "Archivos",
    group: "Eliminación",
    action: "delete",
    isDangerous: true,
    sortOrder: 430,
  }),

  createEntry({
    key: "accounting:dashboard:read",
    label: "Ver resumen contable",
    description: "Permite acceder al tablero base y al resumen general del módulo de contabilidad.",
    module: "Contabilidad",
    group: "Consulta",
    action: "read",
    isDangerous: false,
    sortOrder: 10,
  }),
  ...createCrudPermissionSet({
    prefix: "accounting:transaction",
    module: "Contabilidad",
    subjectPlural: "transacciones contables",
    baseOrder: 100,
    deleteLabel: "Cancelar transacciones contables",
    deleteDescription: "Permite cancelar transacciones registradas en contabilidad.",
  }).map((entry) => (
    entry.key === "accounting:transaction:delete"
      ? { ...entry, key: "accounting:transaction:cancel", action: "cancel", group: "Estados" }
      : entry
  )),
  ...createCrudPermissionSet({
    prefix: "accounting:payable",
    module: "Contabilidad",
    subjectPlural: "cuentas por pagar",
    baseOrder: 200,
    deleteLabel: "Cancelar cuentas por pagar",
    deleteDescription: "Permite cancelar cuentas por pagar registradas.",
  }).flatMap((entry) => {
    if (entry.key === "accounting:payable:delete") {
      return [
        { ...entry, key: "accounting:payable:cancel", action: "cancel", group: "Estados" },
        createEntry({
          key: "accounting:payable:pay",
          label: "Pagar cuentas por pagar",
          description: "Permite registrar pagos y cierres operativos sobre cuentas por pagar.",
          module: "Contabilidad",
          group: "Estados",
          action: "pay",
          isDangerous: true,
          sortOrder: 235,
        }),
      ];
    }
    return entry;
  }),
  ...createCrudPermissionSet({
    prefix: "accounting:donor",
    module: "Contabilidad",
    subjectPlural: "donantes",
    baseOrder: 300,
    deleteLabel: "Editar donantes",
    deleteDescription: "Permite actualizar datos existentes de donantes.",
  }).filter((entry) => entry.key !== "accounting:donor:delete"),
  ...createCrudPermissionSet({
    prefix: "accounting:sponsor",
    module: "Contabilidad",
    subjectPlural: "padrinos",
    baseOrder: 400,
    deleteLabel: "Editar padrinos",
    deleteDescription: "Permite actualizar datos existentes de padrinos.",
  }).filter((entry) => entry.key !== "accounting:sponsor:delete"),
  ...createCrudPermissionSet({
    prefix: "accounting:sponsorship",
    module: "Contabilidad",
    subjectPlural: "apadrinamientos",
    baseOrder: 500,
    deleteLabel: "Cancelar apadrinamientos",
    deleteDescription: "Permite cancelar relaciones activas de apadrinamiento.",
  }).map((entry) => (
    entry.key === "accounting:sponsorship:delete"
      ? { ...entry, key: "accounting:sponsorship:cancel", action: "cancel", group: "Estados" }
      : entry
  )),
  ...createCrudPermissionSet({
    prefix: "accounting:sponsorship_plan",
    module: "Contabilidad",
    subjectPlural: "planes de apadrinamiento",
    baseOrder: 600,
  }),
  createEntry({
    key: "accounting:subscription:read",
    label: "Ver suscripciones",
    description: "Permite consultar suscripciones y su estado de sincronizacion.",
    module: "Contabilidad",
    group: "Consulta",
    action: "read",
    isDangerous: false,
    sortOrder: 710,
  }),
  createEntry({
    key: "accounting:subscription:cancel",
    label: "Cancelar suscripciones",
    description: "Permite cancelar suscripciones activas desde el módulo contable.",
    module: "Contabilidad",
    group: "Estados",
    action: "cancel",
    isDangerous: true,
    sortOrder: 720,
  }),
  createEntry({
    key: "accounting:subscription:sync",
    label: "Sincronizar suscripciones",
    description: "Permite reintentar o sincronizar el estado tecnico de suscripciones externas.",
    module: "Contabilidad",
    group: "Administracion",
    action: "sync",
    isDangerous: true,
    sortOrder: 730,
  }),
  createEntry({
    key: "accounting:subscription_payment:read",
    label: "Ver pagos recurrentes",
    description: "Permite consultar pagos recurrentes y su transaccion contable asociada.",
    module: "Contabilidad",
    group: "Consulta",
    action: "read",
    isDangerous: false,
    sortOrder: 740,
  }),
  createEntry({
    key: "accounting:subscription_payment:create",
    label: "Registrar pagos manuales",
    description: "Permite registrar pagos manuales e integrarlos con su transaccion contable.",
    module: "Contabilidad",
    group: "Creación",
    action: "create",
    isDangerous: true,
    sortOrder: 750,
  }),
  ...createCrudPermissionSet({
    prefix: "accounting:category",
    module: "Contabilidad",
    subjectPlural: "categorias contables",
    baseOrder: 800,
  }),
  ...createCrudPermissionSet({
    prefix: "accounting:payment_provider",
    module: "Contabilidad",
    subjectPlural: "proveedores de pago",
    baseOrder: 900,
    deleteLabel: "Desactivar proveedores de pago",
    deleteDescription: "Permite desactivar proveedores de pago sin eliminarlos físicamente.",
  }),
  ...createCrudPermissionSet({
    prefix: "accounting:payment_order",
    module: "Contabilidad",
    subjectPlural: "ordenes de pago",
    baseOrder: 1000,
    deleteLabel: "Cancelar ordenes de pago",
    deleteDescription: "Permite cancelar ordenes de pago emitidas.",
  }).map((entry) => (
    entry.key === "accounting:payment_order:delete"
      ? { ...entry, key: "accounting:payment_order:cancel", action: "cancel", group: "Estados" }
      : entry
  )),
  createEntry({
    key: "accounting:report:export",
    label: "Exportar reportes contables",
    description: "Permite exportar reportes internos de contabilidad cuando la fase de exportación este habilitada.",
    module: "Contabilidad",
    group: "Reportes",
    action: "export",
    isDangerous: false,
    sortOrder: 1080,
  }),
  createEntry({
    key: "accounting:public_report:read",
    label: "Ver informes públicos contables",
    description: "Permite revisar borradores, informes publicados y su detalle administrativo.",
    module: "Contabilidad",
    group: "Consulta",
    action: "read",
    isDangerous: false,
    sortOrder: 1085,
  }),
  createEntry({
    key: "accounting:public_report:create",
    label: "Generar borradores de informes públicos",
    description: "Permite generar nuevas versiones mensuales en estado borrador.",
    module: "Contabilidad",
    group: "Creación",
    action: "create",
    isDangerous: false,
    sortOrder: 1086,
  }),
  createEntry({
    key: "accounting:public_report:publish",
    label: "Publicar informes públicos contables",
    description: "Permite publicar informes financieros mensuales para consulta pública.",
    module: "Contabilidad",
    group: "Estados",
    action: "publish",
    isDangerous: true,
    sortOrder: 1087,
  }),
  createEntry({
    key: "accounting:public_report:archive",
    label: "Archivar informes públicos contables",
    description: "Permite retirar de circulacion un informe público ya publicado.",
    module: "Contabilidad",
    group: "Estados",
    action: "archive",
    isDangerous: true,
    sortOrder: 1088,
  }),
  createEntry({
    key: "accounting:donation_refund:create",
    label: "Reembolsar donaciones PayPal",
    description: "Permite realizar reembolsos parciales o totales de donaciones PayPal dentro de las primeras 48 horas.",
    module: "Contabilidad",
    group: "Administracion",
    action: "create",
    isDangerous: true,
    sortOrder: 1090,
  }),
  createEntry({
    key: "accounting:webhook:read",
    label: "Ver webhooks contables",
    description: "Permite revisar eventos tecnicos de webhooks asociados a pagos y suscripciones.",
    module: "Contabilidad",
    group: "Historial",
    action: "read_history",
    isDangerous: false,
    sortOrder: 1110,
  }),
  createEntry({
    key: "accounting:webhook:retry",
    label: "Reintentar webhooks contables",
    description: "Permiso reservado para una futura fase; hoy no existe una ruta backend activa para reintento.",
    module: "Contabilidad",
    group: "Administracion",
    action: "retry",
    isDangerous: true,
    sortOrder: 1120,
  }),
];

const moduleOrderMap = new Map(PERMISSION_MODULE_ORDER.map((item, index) => [item, index]));

export const PERMISSION_CATALOG = [...catalogEntries].sort((left, right) => {
  const leftModuleOrder = moduleOrderMap.get(left.module) ?? 999;
  const rightModuleOrder = moduleOrderMap.get(right.module) ?? 999;

  if (leftModuleOrder !== rightModuleOrder) {
    return leftModuleOrder - rightModuleOrder;
  }

  if (left.sortOrder !== right.sortOrder) {
    return left.sortOrder - right.sortOrder;
  }

  return left.label.localeCompare(right.label, "es");
});

function findDuplicateKeys(items = []) {
  const seen = new Set();
  const duplicates = new Set();

  items.forEach((item) => {
    if (seen.has(item.key)) {
      duplicates.add(item.key);
      return;
    }
    seen.add(item.key);
  });

  return Array.from(duplicates).sort();
}

export const PERMISSION_CATALOG_DUPLICATE_KEYS = findDuplicateKeys(PERMISSION_CATALOG);
export const PERMISSION_CATALOG_MISSING_KEYS = ALL_PERMISSION_KEYS
  .filter((key) => !PERMISSION_CATALOG.some((item) => item.key === key))
  .sort();
export const PERMISSION_CATALOG_EXTRA_KEYS = PERMISSION_CATALOG
  .map((item) => item.key)
  .filter((key) => !ALL_PERMISSION_KEYS.includes(key))
  .sort();

export const PERMISSION_CATALOG_REVIEW_REQUIRED = [
  "accounting:webhook:retry",
];

export const PERMISSION_CATALOG_INTEGRITY = {
  totalPermissions: ALL_PERMISSION_KEYS.length,
  catalogEntries: PERMISSION_CATALOG.length,
  duplicateKeys: PERMISSION_CATALOG_DUPLICATE_KEYS,
  missingKeys: PERMISSION_CATALOG_MISSING_KEYS,
  extraKeys: PERMISSION_CATALOG_EXTRA_KEYS,
};

export function getPermissionMetadata(permissionKey) {
  return PERMISSION_CATALOG.find((permission) => permission.key === permissionKey) || {
    key: permissionKey,
    label: "Permiso sin nombre configurado",
    description: "Este permiso requiere revisión del catálogo.",
    module: "Otros",
    group: "Otros",
    action: "unknown",
    isDangerous: false,
    sortOrder: 9999,
  };
}

export function getPermissionLabel(permissionKey) {
  return getPermissionMetadata(permissionKey).label;
}

export function getPermissionDescription(permissionKey) {
  return getPermissionMetadata(permissionKey).description;
}

export function getPermissionGroup(permissionKey) {
  return getPermissionMetadata(permissionKey).group;
}

export function groupPermissionsByModule(permissionKeys = []) {
  return permissionKeys.reduce((groups, permissionKey) => {
    const metadata = getPermissionMetadata(permissionKey);
    const moduleName = metadata.module;

    if (!groups[moduleName]) {
      groups[moduleName] = [];
    }

    groups[moduleName].push(metadata);
    groups[moduleName].sort((left, right) => left.sortOrder - right.sortOrder);

    return groups;
  }, {});
}
