"use strict";

export const CHILE_REGIONS = [
  { clave: "AP", nombre: "Región de Arica y Parinacota", orden: 1 },
  { clave: "TA", nombre: "Región de Tarapacá", orden: 2 },
  { clave: "AN", nombre: "Región de Antofagasta", orden: 3 },
  { clave: "AT", nombre: "Región de Atacama", orden: 4 },
  { clave: "CO", nombre: "Región de Coquimbo", orden: 5 },
  { clave: "VAL", nombre: "Región de Valparaíso", orden: 6 },
  { clave: "RM", nombre: "Región Metropolitana de Santiago", orden: 7 },
  { clave: "OHI", nombre: "Región del Libertador General Bernardo O'Higgins", orden: 8 },
  { clave: "MAU", nombre: "Región del Maule", orden: 9 },
  { clave: "NUB", nombre: "Región de Ñuble", orden: 10 },
  { clave: "BIO", nombre: "Región del Biobío", orden: 11 },
  { clave: "ARA", nombre: "Región de La Araucanía", orden: 12 },
  { clave: "RIO", nombre: "Región de Los Ríos", orden: 13 },
  { clave: "LAG", nombre: "Región de Los Lagos", orden: 14 },
  { clave: "AYS", nombre: "Región de Aysén del General Carlos Ibáñez del Campo", orden: 15 },
  { clave: "MAG", nombre: "Región de Magallanes y de la Antártica Chilena", orden: 16 },
];

export const CHILE_COMMUNES = [
  { regionKey: "AP", nombre: "Arica" },
  { regionKey: "AP", nombre: "Camarones" },
  { regionKey: "AP", nombre: "General Lagos" },
  { regionKey: "AP", nombre: "Putre" },

  { regionKey: "TA", nombre: "Alto Hospicio" },
  { regionKey: "TA", nombre: "Iquique" },
  { regionKey: "TA", nombre: "Camiña" },
  { regionKey: "TA", nombre: "Colchane" },
  { regionKey: "TA", nombre: "Huara" },
  { regionKey: "TA", nombre: "Pica" },
  { regionKey: "TA", nombre: "Pozo Almonte" },

  { regionKey: "AN", nombre: "Antofagasta" },
  { regionKey: "AN", nombre: "Mejillones" },
  { regionKey: "AN", nombre: "Sierra Gorda" },
  { regionKey: "AN", nombre: "Taltal" },
  { regionKey: "AN", nombre: "Calama" },
  { regionKey: "AN", nombre: "Ollagüe" },
  { regionKey: "AN", nombre: "San Pedro de Atacama" },
  { regionKey: "AN", nombre: "María Elena" },
  { regionKey: "AN", nombre: "Tocopilla" },

  { regionKey: "AT", nombre: "Chañaral" },
  { regionKey: "AT", nombre: "Diego de Almagro" },
  { regionKey: "AT", nombre: "Caldera" },
  { regionKey: "AT", nombre: "Copiapó" },
  { regionKey: "AT", nombre: "Tierra Amarilla" },
  { regionKey: "AT", nombre: "Alto del Carmen" },
  { regionKey: "AT", nombre: "Freirina" },
  { regionKey: "AT", nombre: "Huasco" },
  { regionKey: "AT", nombre: "Vallenar" },

  { regionKey: "CO", nombre: "Canela" },
  { regionKey: "CO", nombre: "Illapel" },
  { regionKey: "CO", nombre: "Los Vilos" },
  { regionKey: "CO", nombre: "Salamanca" },
  { regionKey: "CO", nombre: "Andacollo" },
  { regionKey: "CO", nombre: "Coquimbo" },
  { regionKey: "CO", nombre: "La Higuera" },
  { regionKey: "CO", nombre: "La Serena" },
  { regionKey: "CO", nombre: "Paihuano" },
  { regionKey: "CO", nombre: "Vicuña" },
  { regionKey: "CO", nombre: "Combarbalá" },
  { regionKey: "CO", nombre: "Monte Patria" },
  { regionKey: "CO", nombre: "Ovalle" },
  { regionKey: "CO", nombre: "Punitaqui" },
  { regionKey: "CO", nombre: "Río Hurtado" },

  { regionKey: "VAL", nombre: "Isla de Pascua" },
  { regionKey: "VAL", nombre: "Calle Larga" },
  { regionKey: "VAL", nombre: "Los Andes" },
  { regionKey: "VAL", nombre: "Rinconada" },
  { regionKey: "VAL", nombre: "San Esteban" },
  { regionKey: "VAL", nombre: "Limache" },
  { regionKey: "VAL", nombre: "Olmué" },
  { regionKey: "VAL", nombre: "Quilpué" },
  { regionKey: "VAL", nombre: "Villa Alemana" },
  { regionKey: "VAL", nombre: "Cabildo" },
  { regionKey: "VAL", nombre: "La Ligua" },
  { regionKey: "VAL", nombre: "Papudo" },
  { regionKey: "VAL", nombre: "Petorca" },
  { regionKey: "VAL", nombre: "Zapallar" },
  { regionKey: "VAL", nombre: "Hijuelas" },
  { regionKey: "VAL", nombre: "La Calera" },
  { regionKey: "VAL", nombre: "La Cruz" },
  { regionKey: "VAL", nombre: "Nogales" },
  { regionKey: "VAL", nombre: "Quillota" },
  { regionKey: "VAL", nombre: "Algarrobo" },
  { regionKey: "VAL", nombre: "Cartagena" },
  { regionKey: "VAL", nombre: "El Quisco" },
  { regionKey: "VAL", nombre: "El Tabo" },
  { regionKey: "VAL", nombre: "San Antonio" },
  { regionKey: "VAL", nombre: "Santo Domingo" },
  { regionKey: "VAL", nombre: "Catemu" },
  { regionKey: "VAL", nombre: "Llay-Llay" },
  { regionKey: "VAL", nombre: "Panquehue" },
  { regionKey: "VAL", nombre: "Putaendo" },
  { regionKey: "VAL", nombre: "San Felipe" },
  { regionKey: "VAL", nombre: "Santa María" },
  { regionKey: "VAL", nombre: "Casablanca" },
  { regionKey: "VAL", nombre: "Concón" },
  { regionKey: "VAL", nombre: "Juan Fernández" },
  { regionKey: "VAL", nombre: "Puchuncaví" },
  { regionKey: "VAL", nombre: "Quintero" },
  { regionKey: "VAL", nombre: "Valparaíso" },
  { regionKey: "VAL", nombre: "Viña del Mar" },

  { regionKey: "RM", nombre: "Colina" },
  { regionKey: "RM", nombre: "Lampa" },
  { regionKey: "RM", nombre: "Tiltil" },
  { regionKey: "RM", nombre: "Pirque" },
  { regionKey: "RM", nombre: "Puente Alto" },
  { regionKey: "RM", nombre: "San José de Maipo" },
  { regionKey: "RM", nombre: "Buin" },
  { regionKey: "RM", nombre: "Calera de Tango" },
  { regionKey: "RM", nombre: "Paine" },
  { regionKey: "RM", nombre: "San Bernardo" },
  { regionKey: "RM", nombre: "Alhué" },
  { regionKey: "RM", nombre: "Curacaví" },
  { regionKey: "RM", nombre: "María Pinto" },
  { regionKey: "RM", nombre: "Melipilla" },
  { regionKey: "RM", nombre: "San Pedro" },
  { regionKey: "RM", nombre: "Cerrillos" },
  { regionKey: "RM", nombre: "Cerro Navia" },
  { regionKey: "RM", nombre: "Conchalí" },
  { regionKey: "RM", nombre: "El Bosque" },
  { regionKey: "RM", nombre: "Estación Central" },
  { regionKey: "RM", nombre: "Huechuraba" },
  { regionKey: "RM", nombre: "Independencia" },
  { regionKey: "RM", nombre: "La Cisterna" },
  { regionKey: "RM", nombre: "La Granja" },
  { regionKey: "RM", nombre: "La Florida" },
  { regionKey: "RM", nombre: "La Pintana" },
  { regionKey: "RM", nombre: "La Reina" },
  { regionKey: "RM", nombre: "Las Condes" },
  { regionKey: "RM", nombre: "Lo Barnechea" },
  { regionKey: "RM", nombre: "Lo Espejo" },
  { regionKey: "RM", nombre: "Lo Prado" },
  { regionKey: "RM", nombre: "Macul" },
  { regionKey: "RM", nombre: "Maipú" },
  { regionKey: "RM", nombre: "Ñuñoa" },
  { regionKey: "RM", nombre: "Pedro Aguirre Cerda" },
  { regionKey: "RM", nombre: "Peñalolén" },
  { regionKey: "RM", nombre: "Providencia" },
  { regionKey: "RM", nombre: "Pudahuel" },
  { regionKey: "RM", nombre: "Quilicura" },
  { regionKey: "RM", nombre: "Quinta Normal" },
  { regionKey: "RM", nombre: "Recoleta" },
  { regionKey: "RM", nombre: "Renca" },
  { regionKey: "RM", nombre: "San Miguel" },
  { regionKey: "RM", nombre: "San Joaquín" },
  { regionKey: "RM", nombre: "San Ramón" },
  { regionKey: "RM", nombre: "Santiago" },
  { regionKey: "RM", nombre: "Vitacura" },
  { regionKey: "RM", nombre: "El Monte" },
  { regionKey: "RM", nombre: "Isla de Maipo" },
  { regionKey: "RM", nombre: "Padre Hurtado" },
  { regionKey: "RM", nombre: "Peñaflor" },
  { regionKey: "RM", nombre: "Talagante" },

  { regionKey: "OHI", nombre: "Codegua" },
  { regionKey: "OHI", nombre: "Coínco" },
  { regionKey: "OHI", nombre: "Coltauco" },
  { regionKey: "OHI", nombre: "Doñihue" },
  { regionKey: "OHI", nombre: "Graneros" },
  { regionKey: "OHI", nombre: "Las Cabras" },
  { regionKey: "OHI", nombre: "Machalí" },
  { regionKey: "OHI", nombre: "Malloa" },
  { regionKey: "OHI", nombre: "Olivar" },
  { regionKey: "OHI", nombre: "Peumo" },
  { regionKey: "OHI", nombre: "Pichidegua" },
  { regionKey: "OHI", nombre: "Quinta de Tilcoco" },
  { regionKey: "OHI", nombre: "Rancagua" },
  { regionKey: "OHI", nombre: "Requínoa" },
  { regionKey: "OHI", nombre: "Rengo" },
  { regionKey: "OHI", nombre: "San Francisco de Mostazal" },
  { regionKey: "OHI", nombre: "San Vicente de Tagua Tagua" },
  { regionKey: "OHI", nombre: "La Estrella" },
  { regionKey: "OHI", nombre: "Litueche" },
  { regionKey: "OHI", nombre: "Marchigüe" },
  { regionKey: "OHI", nombre: "Navidad" },
  { regionKey: "OHI", nombre: "Paredones" },
  { regionKey: "OHI", nombre: "Pichilemu" },
  { regionKey: "OHI", nombre: "Chépica" },
  { regionKey: "OHI", nombre: "Chimbarongo" },
  { regionKey: "OHI", nombre: "Lolol" },
  { regionKey: "OHI", nombre: "Nancagua" },
  { regionKey: "OHI", nombre: "Palmilla" },
  { regionKey: "OHI", nombre: "Peralillo" },
  { regionKey: "OHI", nombre: "Placilla" },
  { regionKey: "OHI", nombre: "Pumanque" },
  { regionKey: "OHI", nombre: "San Fernando" },
  { regionKey: "OHI", nombre: "Santa Cruz" },

  { regionKey: "MAU", nombre: "Cauquenes" },
  { regionKey: "MAU", nombre: "Chanco" },
  { regionKey: "MAU", nombre: "Pelluhue" },
  { regionKey: "MAU", nombre: "Curicó" },
  { regionKey: "MAU", nombre: "Hualañé" },
  { regionKey: "MAU", nombre: "Licantén" },
  { regionKey: "MAU", nombre: "Molina" },
  { regionKey: "MAU", nombre: "Rauco" },
  { regionKey: "MAU", nombre: "Romeral" },
  { regionKey: "MAU", nombre: "Sagrada Familia" },
  { regionKey: "MAU", nombre: "Teno" },
  { regionKey: "MAU", nombre: "Vichuquén" },
  { regionKey: "MAU", nombre: "Colbún" },
  { regionKey: "MAU", nombre: "Linares" },
  { regionKey: "MAU", nombre: "Longaví" },
  { regionKey: "MAU", nombre: "Parral" },
  { regionKey: "MAU", nombre: "Retiro" },
  { regionKey: "MAU", nombre: "San Javier" },
  { regionKey: "MAU", nombre: "Villa Alegre" },
  { regionKey: "MAU", nombre: "Yerbas Buenas" },
  { regionKey: "MAU", nombre: "Constitución" },
  { regionKey: "MAU", nombre: "Curepto" },
  { regionKey: "MAU", nombre: "Empedrado" },
  { regionKey: "MAU", nombre: "Maule" },
  { regionKey: "MAU", nombre: "Pelarco" },
  { regionKey: "MAU", nombre: "Pencahue" },
  { regionKey: "MAU", nombre: "Río Claro" },
  { regionKey: "MAU", nombre: "San Clemente" },
  { regionKey: "MAU", nombre: "San Rafael" },
  { regionKey: "MAU", nombre: "Talca" },

  { regionKey: "NUB", nombre: "Bulnes" },
  { regionKey: "NUB", nombre: "Chillán" },
  { regionKey: "NUB", nombre: "Chillán Viejo" },
  { regionKey: "NUB", nombre: "El Carmen" },
  { regionKey: "NUB", nombre: "Pemuco" },
  { regionKey: "NUB", nombre: "Pinto" },
  { regionKey: "NUB", nombre: "Quillón" },
  { regionKey: "NUB", nombre: "San Ignacio" },
  { regionKey: "NUB", nombre: "Yungay" },
  { regionKey: "NUB", nombre: "Cobquecura" },
  { regionKey: "NUB", nombre: "Coelemu" },
  { regionKey: "NUB", nombre: "Ninhue" },
  { regionKey: "NUB", nombre: "Portezuelo" },
  { regionKey: "NUB", nombre: "Quirihue" },
  { regionKey: "NUB", nombre: "Ránquil" },
  { regionKey: "NUB", nombre: "Treguaco" },
  { regionKey: "NUB", nombre: "Coihueco" },
  { regionKey: "NUB", nombre: "Ñiquén" },
  { regionKey: "NUB", nombre: "San Carlos" },
  { regionKey: "NUB", nombre: "San Fabián" },
  { regionKey: "NUB", nombre: "San Nicolás" },

  { regionKey: "BIO", nombre: "Arauco" },
  { regionKey: "BIO", nombre: "Cañete" },
  { regionKey: "BIO", nombre: "Contulmo" },
  { regionKey: "BIO", nombre: "Curanilahue" },
  { regionKey: "BIO", nombre: "Lebu" },
  { regionKey: "BIO", nombre: "Los Álamos" },
  { regionKey: "BIO", nombre: "Tirúa" },
  { regionKey: "BIO", nombre: "Alto Biobío" },
  { regionKey: "BIO", nombre: "Antuco" },
  { regionKey: "BIO", nombre: "Cabrero" },
  { regionKey: "BIO", nombre: "Laja" },
  { regionKey: "BIO", nombre: "Los Ángeles" },
  { regionKey: "BIO", nombre: "Mulchén" },
  { regionKey: "BIO", nombre: "Nacimiento" },
  { regionKey: "BIO", nombre: "Negrete" },
  { regionKey: "BIO", nombre: "Quilaco" },
  { regionKey: "BIO", nombre: "Quilleco" },
  { regionKey: "BIO", nombre: "San Rosendo" },
  { regionKey: "BIO", nombre: "Santa Bárbara" },
  { regionKey: "BIO", nombre: "Tucapel" },
  { regionKey: "BIO", nombre: "Yumbel" },
  { regionKey: "BIO", nombre: "Chiguayante" },
  { regionKey: "BIO", nombre: "Concepción" },
  { regionKey: "BIO", nombre: "Coronel" },
  { regionKey: "BIO", nombre: "Florida" },
  { regionKey: "BIO", nombre: "Hualpén" },
  { regionKey: "BIO", nombre: "Hualqui" },
  { regionKey: "BIO", nombre: "Lota" },
  { regionKey: "BIO", nombre: "Penco" },
  { regionKey: "BIO", nombre: "San Pedro de la Paz" },
  { regionKey: "BIO", nombre: "Santa Juana" },
  { regionKey: "BIO", nombre: "Talcahuano" },
  { regionKey: "BIO", nombre: "Tomé" },

  { regionKey: "ARA", nombre: "Carahue" },
  { regionKey: "ARA", nombre: "Cholchol" },
  { regionKey: "ARA", nombre: "Cunco" },
  { regionKey: "ARA", nombre: "Curarrehue" },
  { regionKey: "ARA", nombre: "Freire" },
  { regionKey: "ARA", nombre: "Galvarino" },
  { regionKey: "ARA", nombre: "Gorbea" },
  { regionKey: "ARA", nombre: "Lautaro" },
  { regionKey: "ARA", nombre: "Loncoche" },
  { regionKey: "ARA", nombre: "Melipeuco" },
  { regionKey: "ARA", nombre: "Nueva Imperial" },
  { regionKey: "ARA", nombre: "Padre Las Casas" },
  { regionKey: "ARA", nombre: "Perquenco" },
  { regionKey: "ARA", nombre: "Pitrufquén" },
  { regionKey: "ARA", nombre: "Pucón" },
  { regionKey: "ARA", nombre: "Puerto Saavedra" },
  { regionKey: "ARA", nombre: "Temuco" },
  { regionKey: "ARA", nombre: "Teodoro Schmidt" },
  { regionKey: "ARA", nombre: "Toltén" },
  { regionKey: "ARA", nombre: "Vilcún" },
  { regionKey: "ARA", nombre: "Villarrica" },
  { regionKey: "ARA", nombre: "Angol" },
  { regionKey: "ARA", nombre: "Collipulli" },
  { regionKey: "ARA", nombre: "Curacautín" },
  { regionKey: "ARA", nombre: "Ercilla" },
  { regionKey: "ARA", nombre: "Lonquimay" },
  { regionKey: "ARA", nombre: "Los Sauces" },
  { regionKey: "ARA", nombre: "Lumaco" },
  { regionKey: "ARA", nombre: "Purén" },
  { regionKey: "ARA", nombre: "Renaico" },
  { regionKey: "ARA", nombre: "Traiguén" },
  { regionKey: "ARA", nombre: "Victoria" },

  { regionKey: "RIO", nombre: "Futrono" },
  { regionKey: "RIO", nombre: "La Unión" },
  { regionKey: "RIO", nombre: "Lago Ranco" },
  { regionKey: "RIO", nombre: "Río Bueno" },
  { regionKey: "RIO", nombre: "Corral" },
  { regionKey: "RIO", nombre: "Lanco" },
  { regionKey: "RIO", nombre: "Los Lagos" },
  { regionKey: "RIO", nombre: "Máfil" },
  { regionKey: "RIO", nombre: "Mariquina" },
  { regionKey: "RIO", nombre: "Paillaco" },
  { regionKey: "RIO", nombre: "Panguipulli" },
  { regionKey: "RIO", nombre: "Valdivia" },

  { regionKey: "LAG", nombre: "Ancud" },
  { regionKey: "LAG", nombre: "Castro" },
  { regionKey: "LAG", nombre: "Chonchi" },
  { regionKey: "LAG", nombre: "Curaco de Vélez" },
  { regionKey: "LAG", nombre: "Dalcahue" },
  { regionKey: "LAG", nombre: "Puqueldón" },
  { regionKey: "LAG", nombre: "Queilén" },
  { regionKey: "LAG", nombre: "Quellón" },
  { regionKey: "LAG", nombre: "Quemchi" },
  { regionKey: "LAG", nombre: "Quinchao" },
  { regionKey: "LAG", nombre: "Calbuco" },
  { regionKey: "LAG", nombre: "Cochamó" },
  { regionKey: "LAG", nombre: "Fresia" },
  { regionKey: "LAG", nombre: "Frutillar" },
  { regionKey: "LAG", nombre: "Llanquihue" },
  { regionKey: "LAG", nombre: "Los Muermos" },
  { regionKey: "LAG", nombre: "Maullín" },
  { regionKey: "LAG", nombre: "Puerto Montt" },
  { regionKey: "LAG", nombre: "Puerto Varas" },
  { regionKey: "LAG", nombre: "Osorno" },
  { regionKey: "LAG", nombre: "Puerto Octay" },
  { regionKey: "LAG", nombre: "Purranque" },
  { regionKey: "LAG", nombre: "Puyehue" },
  { regionKey: "LAG", nombre: "Río Negro" },
  { regionKey: "LAG", nombre: "San Juan de la Costa" },
  { regionKey: "LAG", nombre: "San Pablo" },
  { regionKey: "LAG", nombre: "Chaitén" },
  { regionKey: "LAG", nombre: "Futaleufú" },
  { regionKey: "LAG", nombre: "Hualaihué" },
  { regionKey: "LAG", nombre: "Palena" },

  { regionKey: "AYS", nombre: "Aysén" },
  { regionKey: "AYS", nombre: "Cisnes" },
  { regionKey: "AYS", nombre: "Guaitecas" },
  { regionKey: "AYS", nombre: "Cochrane" },
  { regionKey: "AYS", nombre: "O'Higgins" },
  { regionKey: "AYS", nombre: "Tortel" },
  { regionKey: "AYS", nombre: "Coyhaique" },
  { regionKey: "AYS", nombre: "Lago Verde" },
  { regionKey: "AYS", nombre: "Chile Chico" },
  { regionKey: "AYS", nombre: "Río Ibáñez" },

  { regionKey: "MAG", nombre: "Antártica" },
  { regionKey: "MAG", nombre: "Cabo de Hornos" },
  { regionKey: "MAG", nombre: "Laguna Blanca" },
  { regionKey: "MAG", nombre: "Punta Arenas" },
  { regionKey: "MAG", nombre: "Río Verde" },
  { regionKey: "MAG", nombre: "San Gregorio" },
  { regionKey: "MAG", nombre: "Porvenir" },
  { regionKey: "MAG", nombre: "Primavera" },
  { regionKey: "MAG", nombre: "Timaukel" },
  { regionKey: "MAG", nombre: "Natales" },
  { regionKey: "MAG", nombre: "Torres del Paine" },
];

export function getChileCommunesCount() {
  return CHILE_COMMUNES.length;
}
